// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class GenreIdchangedtointtypeinMovietomatchIdinGenreclass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GenreIdchangedtointtypeinMovietomatchIdinGenreclass));
        
        string IMigrationMetadata.Id
        {
            get { return "202401310139196_GenreId changed to int type in Movie to match Id in Genre class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
